#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-zeep
Version  : 4.1.0
Release  : 44
URL      : https://github.com/mvantellingen/python-zeep/archive/4.1.0/python-zeep-4.1.0.tar.gz
Source0  : https://github.com/mvantellingen/python-zeep/archive/4.1.0/python-zeep-4.1.0.tar.gz
Summary  : A modern/fast Python SOAP client based on lxml / requests
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: python-zeep-license = %{version}-%{release}
Requires: python-zeep-python = %{version}-%{release}
Requires: python-zeep-python3 = %{version}-%{release}
Requires: pypi(requests_toolbelt)
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv
BuildRequires : requests-toolbelt-python

%description
========================
Zeep: Python SOAP client
========================
A fast and modern Python SOAP client

%package license
Summary: license components for the python-zeep package.
Group: Default

%description license
license components for the python-zeep package.


%package python
Summary: python components for the python-zeep package.
Group: Default
Requires: python-zeep-python3 = %{version}-%{release}

%description python
python components for the python-zeep package.


%package python3
Summary: python3 components for the python-zeep package.
Group: Default
Requires: python3-core
Provides: pypi(python_zeep)
Requires: pypi(appdirs)
Requires: pypi(attrs)
Requires: pypi(cached_property)
Requires: pypi(defusedxml)
Requires: pypi(isodate)
Requires: pypi(lxml)
Requires: pypi(pytz)
Requires: pypi(requests)
Requires: pypi(requests_toolbelt)
Requires: pypi(six)

%description python3
python3 components for the python-zeep package.


%prep
%setup -q -n python-zeep-4.1.0
cd %{_builddir}/python-zeep-4.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641840816
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-zeep
cp %{_builddir}/python-zeep-4.1.0/LICENSE %{buildroot}/usr/share/package-licenses/python-zeep/0ec11e70fb9dd0c965ea38fadc03cb37eef008fd
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-zeep/0ec11e70fb9dd0c965ea38fadc03cb37eef008fd

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
