#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-zeep
Version  : 4.2.0
Release  : 48
URL      : https://github.com/mvantellingen/python-zeep/archive/4.2.0/python-zeep-4.2.0.tar.gz
Source0  : https://github.com/mvantellingen/python-zeep/archive/4.2.0/python-zeep-4.2.0.tar.gz
Summary  : A modern/fast Python SOAP client based on lxml / requests
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: python-zeep-python = %{version}-%{release}
Requires: python-zeep-python3 = %{version}-%{release}
Requires: pypi(requests_file)
Requires: pypi(requests_toolbelt)
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi(requests_toolbelt)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
========================
Zeep: Python SOAP client
========================
A fast and modern Python SOAP client

%package python
Summary: python components for the python-zeep package.
Group: Default
Requires: python-zeep-python3 = %{version}-%{release}

%description python
python components for the python-zeep package.


%package python3
Summary: python3 components for the python-zeep package.
Group: Default
Requires: python3-core
Provides: pypi(python_zeep)
Requires: pypi(appdirs)
Requires: pypi(attrs)
Requires: pypi(cached_property)
Requires: pypi(defusedxml)
Requires: pypi(isodate)
Requires: pypi(lxml)
Requires: pypi(pytz)
Requires: pypi(requests)
Requires: pypi(requests_toolbelt)
Requires: pypi(six)

%description python3
python3 components for the python-zeep package.


%prep
%setup -q -n python-zeep-4.2.0
cd %{_builddir}/python-zeep-4.2.0
pushd ..
cp -a python-zeep-4.2.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1667486536
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
